export const NoOfDays = [
  { value: 1, label: "Day 1" },
  { value: 2, label: "Day 2" },
  { value: 3, label: "Day 3" },
  { value: 4, label: "Day 4" },
  { value: 5, label: "Day 5" },
  { value: 6, label: "Day 6" },
  { value: 7, label: "Day 7" },
  { value: 8, label: "Day 8" },
  { value: 9, label: "Day 9" },
  { value: 10, label: "Day 10" },
  { value: 11, label: "Day 11" },
  { value: 12, label: "Day 12" },
  { value: 13, label: "Day 13" },
  { value: 14, label: "Day 14" },
  { value: 15, label: "Day 15" },
  { value: 16, label: "Day 16" },
  { value: 17, label: "Day 17" },
  { value: 18, label: "Day 18" },
  { value: 19, label: "Day 19" },
  { value: 20, label: "Day 20" },
  { value: 21, label: "Day 21" },
  { value: 22, label: "Day 22" },
  { value: 23, label: "Day 23" },
  { value: 24, label: "Day 24" },
  { value: 25, label: "Day 25" },
  { value: 26, label: "Day 26" },
  { value: 27, label: "Day 27" },
  { value: 28, label: "Day 28" },
  { value: 29, label: "Day 29" },
  { value: 30, label: "Day 30" },
];

export const options = [
  { value: "HR", label: "HR" },
  { value: "BackEndDeveloper", label: "BackEnd Developer" },
  { value: "UIDeveloper", label: "UI Developer" },
  { value: "UXDeveloper", label: "UX Developer" },
];
